import type { CPU, Motherboard, RAM, SSD, GPU, PSU, PCCase, Cooler } from "./types";

export const CPUS: CPU[] = [
  { id: "cpu-01", category: "cpu", brand: "AMD", tier: "라이젠3", model: "3300X", codename: "마티스", socket: "AM4", cores_threads: "4C/8T", base_ghz: 3.8, boost_ghz: 4.3, cache: "2MB/16MB", tdp_w: 65, memory: "DDR4-3200", extra: null },
  { id: "cpu-02", category: "cpu", brand: "AMD", tier: "라이젠3", model: "4100", codename: "르누아르-X", socket: "AM4", cores_threads: "4C/8T", base_ghz: 3.8, boost_ghz: 4, cache: "2MB/4MB", tdp_w: 65, memory: "DDR4-3200", extra: null },
  { id: "cpu-03", category: "cpu", brand: "AMD", tier: "라이젠3", model: "3100", codename: "마티스", socket: "AM4", cores_threads: "4C/8T", base_ghz: 3.6, boost_ghz: 3.9, cache: "2MB/16MB", tdp_w: 65, memory: "DDR4-3200", extra: null },
  { id: "cpu-04", category: "cpu", brand: "AMD", tier: "라이젠5", model: "9600X", codename: "그래니트 릿지", socket: "AM5", cores_threads: "6C/12T", base_ghz: 3.9, boost_ghz: 5.4, cache: "6MB/32MB", tdp_w: 65, memory: "DDR5-5600", extra: {"tdp_max_ppt_w": 88} },
  { id: "cpu-05", category: "cpu", brand: "AMD", tier: "라이젠5", model: "5600X", codename: "버미어", socket: "AM4", cores_threads: "6C/12T", base_ghz: 3.7, boost_ghz: 4.6, cache: "3MB/32MB", tdp_w: 65, memory: "DDR4-3200", extra: null },
  { id: "cpu-06", category: "cpu", brand: "AMD", tier: "라이젠5", model: "7600", codename: "라파엘", socket: "AM5", cores_threads: "6C/12T", base_ghz: 3.8, boost_ghz: 5.1, cache: "6MB/32MB", tdp_w: 65, memory: "DDR5-5200", extra: {"has_igpu": true} },
  { id: "cpu-07", category: "cpu", brand: "AMD", tier: "라이젠7", model: "7800X3D", codename: "라파엘", socket: "AM5", cores_threads: "8C/16T", base_ghz: 4.2, boost_ghz: 5, cache: "8MB/96MB", tdp_w: 120, memory: "DDR5-5200", extra: {"v_cache": true} },
  { id: "cpu-08", category: "cpu", brand: "AMD", tier: "라이젠7", model: "5700X", codename: "버미어", socket: "AM4", cores_threads: "8C/16T", base_ghz: 3.4, boost_ghz: 4.6, cache: "4MB/32MB", tdp_w: 65, memory: "DDR4-3200", extra: null },
  { id: "cpu-09", category: "cpu", brand: "AMD", tier: "라이젠5", model: "5600", codename: "버미어", socket: "AM4", cores_threads: "6C/12T", base_ghz: 3.5, boost_ghz: 4.4, cache: "3MB/32MB", tdp_w: 65, memory: "DDR4-3200", extra: {"has_igpu": false} },
  { id: "cpu-10", category: "cpu", brand: "AMD", tier: "라이젠7", model: "5800X3D", codename: "버미어", socket: "AM4", cores_threads: "8C/16T", base_ghz: 3.4, boost_ghz: 4.5, cache: "4MB/96MB", tdp_w: 105, memory: "DDR4-3200", extra: {"v_cache": true} },
  { id: "cpu-11", category: "cpu", brand: "AMD", tier: "라이젠7", model: "5700X3D", codename: "버미어", socket: "AM4", cores_threads: "8C/16T", base_ghz: 3, boost_ghz: 4.1, cache: "4MB/96MB", tdp_w: 105, memory: "DDR4-3200", extra: {"v_cache": true} },
  { id: "cpu-12", category: "cpu", brand: "Intel", tier: "i3", model: "14100", codename: null, socket: "LGA1700", cores_threads: "4C/8T", base_ghz: 3.5, boost_ghz: 4.7, cache: "5MB/12MB", tdp_w: 60, memory: "DDR5-4800/DDR4-3200", extra: {"tdp_range_w": "60-110"} },
  { id: "cpu-13", category: "cpu", brand: "Intel", tier: "i3", model: "13100F", codename: null, socket: "LGA1700", cores_threads: "4C/8T", base_ghz: 3.4, boost_ghz: 4.5, cache: "5MB/12MB", tdp_w: 58, memory: "DDR5-4800/DDR4-3200", extra: {"tdp_range_w": "58-89"} },
  { id: "cpu-14", category: "cpu", brand: "Intel", tier: "i3", model: "13100", codename: null, socket: "LGA1700", cores_threads: "4C/8T", base_ghz: 3.4, boost_ghz: 4.5, cache: "5MB/12MB", tdp_w: 60, memory: "DDR5-4800/DDR4-3200", extra: {"tdp_range_w": "60-110"} },
  { id: "cpu-15", category: "cpu", brand: "Intel", tier: "Ultra 9", model: "285K", codename: "애로우레이크", socket: "LGA1851", cores_threads: "24C/24T", base_ghz: 3.7, boost_ghz: 5.7, cache: "36MB", tdp_w: 125, memory: "DDR5-6400", extra: null },
  { id: "cpu-16", category: "cpu", brand: "Intel", tier: "Ultra 7", model: "265K", codename: "애로우레이크", socket: "LGA1851", cores_threads: "20C/20T", base_ghz: 3.9, boost_ghz: 5.5, cache: "30MB", tdp_w: 125, memory: "DDR5-6400", extra: null },
  { id: "cpu-17", category: "cpu", brand: "Intel", tier: "Ultra 5", model: "245K", codename: "애로우레이크", socket: "LGA1851", cores_threads: "14C/14T", base_ghz: 4.2, boost_ghz: 5.2, cache: "24MB", tdp_w: 125, memory: "DDR5-6400", extra: null },
  { id: "cpu-18", category: "cpu", brand: "Intel", tier: "i9", model: "14900K", codename: "랩터레이크-R", socket: "LGA1700", cores_threads: "24C/32T", base_ghz: 3.2, boost_ghz: 6, cache: "36MB", tdp_w: 125, memory: "DDR5-5600/DDR4-3200", extra: null },
  { id: "cpu-19", category: "cpu", brand: "Intel", tier: "i7", model: "14700K", codename: "랩터레이크-R", socket: "LGA1700", cores_threads: "20C/28T", base_ghz: 3.4, boost_ghz: 5.6, cache: "33MB", tdp_w: 125, memory: "DDR5-5600/DDR4-3200", extra: null },
  { id: "cpu-20", category: "cpu", brand: "Intel", tier: "i5", model: "14600K", codename: "랩터레이크-R", socket: "LGA1700", cores_threads: "14C/20T", base_ghz: 3.5, boost_ghz: 5.3, cache: "24MB", tdp_w: 125, memory: "DDR5-5600/DDR4-3200", extra: null },
  { id: "cpu-21", category: "cpu", brand: "Intel", tier: "i5", model: "13400F", codename: "랩터레이크", socket: "LGA1700", cores_threads: "10C/16T", base_ghz: 2.5, boost_ghz: 4.6, cache: "20MB", tdp_w: 65, memory: "DDR5-4800/DDR4-3200", extra: null },
  { id: "cpu-22", category: "cpu", brand: "AMD", tier: "라이젠7", model: "9800X3D", codename: "그래니트 릿지", socket: "AM5", cores_threads: "8C/16T", base_ghz: 4.7, boost_ghz: 5.2, cache: "96MB", tdp_w: 120, memory: "DDR5-5600", extra: {"v_cache": true} },
  { id: "cpu-23", category: "cpu", brand: "AMD", tier: "라이젠9", model: "9950X", codename: "그래니트 릿지", socket: "AM5", cores_threads: "16C/32T", base_ghz: 4.3, boost_ghz: 5.7, cache: "64MB", tdp_w: 170, memory: "DDR5-5600", extra: null },
  { id: "cpu-24", category: "cpu", brand: "AMD", tier: "라이젠7", model: "9700X", codename: "그래니트 릿지", socket: "AM5", cores_threads: "8C/16T", base_ghz: 3.8, boost_ghz: 5.5, cache: "32MB", tdp_w: 65, memory: "DDR5-5600", extra: null },
  { id: "cpu-25", category: "cpu", brand: "AMD", tier: "라이젠5", model: "7500F", codename: "라파엘", socket: "AM5", cores_threads: "6C/12T", base_ghz: 3.7, boost_ghz: 5, cache: "32MB", tdp_w: 65, memory: "DDR5-5200", extra: {"has_igpu": false} },
  { id: "cpu-26", category: "cpu", brand: "Intel", tier: "i5", model: "14400F", codename: "랩터레이크-R", socket: "LGA1700", cores_threads: "10C/16T", base_ghz: 2.5, boost_ghz: 4.7, cache: "20MB", tdp_w: 65, memory: "DDR5-4800/DDR4-3200", extra: null },
  { id: "cpu-27", category: "cpu", brand: "Intel", tier: "i5", model: "12400F", codename: "엘더레이크", socket: "LGA1700", cores_threads: "6C/12T", base_ghz: 2.5, boost_ghz: 4.4, cache: "18MB", tdp_w: 65, memory: "DDR4-3200/DDR5-4800", extra: null },
  { id: "cpu-28", category: "cpu", brand: "AMD", tier: "라이젠5", model: "5600G", codename: "세잔", socket: "AM4", cores_threads: "6C/12T", base_ghz: 3.9, boost_ghz: 4.4, cache: "3MB/16MB", tdp_w: 65, memory: "DDR4-3200", extra: {"has_igpu": true, "gpu_model": "Radeon Vega 7"} },
];

export const MOTHERBOARDS: Motherboard[] = [
  { id: "mb-01", category: "motherboard", model: "ASUS PRIME B650M-A II", socket: "AM5", chipset: "B650", form_factor: "M-ATX", width_mm: 244, depth_mm: 244, pcie_x16_usable_slots: 1, pcie_x16_total_slots: 3, memory_type: "DDR5", extra: null },
  { id: "mb-02", category: "motherboard", model: "ASUS TUF GAMING B650-PLUS", socket: "AM5", chipset: "B650", form_factor: "ATX", width_mm: 305, depth_mm: 244, pcie_x16_usable_slots: 2, pcie_x16_total_slots: 2, memory_type: "DDR5", extra: {"pcie_x1_slots": 2} },
  { id: "mb-03", category: "motherboard", model: "ASUS ROG STRIX X870E-E GAMING WIFI", socket: "AM5", chipset: "X870E", form_factor: "ATX", width_mm: 305, depth_mm: 244, pcie_x16_usable_slots: 2, pcie_x16_total_slots: null, memory_type: "DDR5", extra: null },
  { id: "mb-04", category: "motherboard", model: "GIGABYTE B650M AORUS ELITE", socket: "AM5", chipset: "B650", form_factor: "M-ATX", width_mm: 244, depth_mm: 244, pcie_x16_usable_slots: 1, pcie_x16_total_slots: 3, memory_type: "DDR5", extra: null },
  { id: "mb-05", category: "motherboard", model: "GIGABYTE X870 AORUS ELITE WIFI7", socket: "AM5", chipset: "X870", form_factor: "ATX", width_mm: 305, depth_mm: 244, pcie_x16_usable_slots: 3, pcie_x16_total_slots: null, memory_type: "DDR5", extra: null },
  { id: "mb-06", category: "motherboard", model: "GIGABYTE B760M AORUS ELITE D4 Gen5", socket: "LGA1700", chipset: "B760", form_factor: "M-ATX", width_mm: 244, depth_mm: 244, pcie_x16_usable_slots: 2, pcie_x16_total_slots: null, memory_type: "DDR4", extra: null },
  { id: "mb-07", category: "motherboard", model: "GIGABYTE Z890 AORUS ELITE WIFI7", socket: "LGA1851", chipset: "Z890", form_factor: "ATX", width_mm: 305, depth_mm: 244, pcie_x16_usable_slots: 2, pcie_x16_total_slots: null, memory_type: "DDR5", extra: {"pcie_note": "자료마다 표기 다름, 재확인 필요"} },
  { id: "mb-08", category: "motherboard", model: "MSI MAG B650M 박격포 WIFI", socket: "AM5", chipset: "B650", form_factor: "M-ATX", width_mm: 244, depth_mm: 244, pcie_x16_usable_slots: 1, pcie_x16_total_slots: 2, memory_type: "DDR5", extra: {"pcie_x1_slots": 1} },
  { id: "mb-09", category: "motherboard", model: "MSI PRO B650M-A WIFI", socket: "AM5", chipset: "B650", form_factor: "M-ATX", width_mm: 244, depth_mm: 244, pcie_x16_usable_slots: 1, pcie_x16_total_slots: 2, memory_type: "DDR5", extra: {"pcie_x1_slots": 1} },
  { id: "mb-10", category: "motherboard", model: "MSI MPG X870E 엣지 TI WIFI", socket: "AM5", chipset: "X870E", form_factor: "ATX", width_mm: 305, depth_mm: 244, pcie_x16_usable_slots: 3, pcie_x16_total_slots: null, memory_type: "DDR5", extra: null },
  { id: "mb-11", category: "motherboard", model: "MSI MAG B760M 박격포 II", socket: "LGA1700", chipset: "B760", form_factor: "M-ATX", width_mm: 244, depth_mm: 244, pcie_x16_usable_slots: 1, pcie_x16_total_slots: null, memory_type: "DDR5", extra: {"pcie_x4_slots": 1} },
  { id: "mb-12", category: "motherboard", model: "MSI PRO B760M-A DDR4 II", socket: "LGA1700", chipset: "B760", form_factor: "M-ATX", width_mm: 244, depth_mm: 244, pcie_x16_usable_slots: 1, pcie_x16_total_slots: 2, memory_type: "DDR4", extra: {"pcie_x1_slots": 1} },
  { id: "mb-13", category: "motherboard", model: "ASRock B650M PRO RS/X3D", socket: "AM5", chipset: "B650", form_factor: "M-ATX", width_mm: 244, depth_mm: 244, pcie_x16_usable_slots: 1, pcie_x16_total_slots: null, memory_type: "DDR5", extra: {"pcie_x4_slots": 1} },
  { id: "mb-14", category: "motherboard", model: "ASRock B650E PG-ITX/WiFi", socket: "AM5", chipset: "B650E", form_factor: "Mini-ITX", width_mm: 170, depth_mm: 170, pcie_x16_usable_slots: 1, pcie_x16_total_slots: 1, memory_type: "DDR5", extra: {"note": "확장슬롯 1개뿐, 추가 확장카드 불가"} },
  { id: "mb-15", category: "motherboard", model: "ASRock B760M Steel Legend", socket: "LGA1700", chipset: "B760", form_factor: "M-ATX", width_mm: 244, depth_mm: 244, pcie_x16_usable_slots: 1, pcie_x16_total_slots: null, memory_type: "DDR5", extra: {"pcie_x1_slots": 1} },
  { id: "mb-16", category: "motherboard", model: "ASRock Z890 PRO-A WiFi", socket: "LGA1851", chipset: "Z890", form_factor: "ATX", width_mm: 305, depth_mm: 244, pcie_x16_usable_slots: 1, pcie_x16_total_slots: null, memory_type: "DDR5", extra: {"pcie_x4_slots": 2, "pcie_x1_slots": 1} },
];

export const RAMS: RAM[] = [
  { id: "ram-01", category: "ram", type: "DDR5", model: "삼성전자 DDR5-5600 벌크", speed_mhz: 5600, heatsink_height_mm: null, voltage_v: 1.1, extra: null },
  { id: "ram-02", category: "ram", type: "DDR5", model: "SK하이닉스 DDR5-5600 16GB", speed_mhz: 5600, heatsink_height_mm: null, voltage_v: 1.1, extra: null },
  { id: "ram-03", category: "ram", type: "DDR5", model: "ESSENCORE KLEVV DDR5-5600 CL46", speed_mhz: 5600, heatsink_height_mm: null, voltage_v: 1.1, extra: null },
  { id: "ram-04", category: "ram", type: "DDR5", model: "ADATA XPG LANCER BLADE RGB DDR5-6000", speed_mhz: 6000, heatsink_height_mm: 42, voltage_v: 1.35, extra: null },
  { id: "ram-05", category: "ram", type: "DDR5", model: "팀그룹 T-Force DELTA RGB DDR5-6000", speed_mhz: 6000, heatsink_height_mm: 45.1, voltage_v: 1.35, extra: null },
  { id: "ram-06", category: "ram", type: "DDR4", model: "SK하이닉스 DDR4-3200 벌크", speed_mhz: 3200, heatsink_height_mm: null, voltage_v: 1.2, extra: null },
  { id: "ram-07", category: "ram", type: "DDR4", model: "지스킬 Trident Z RGB DDR4-3200", speed_mhz: 3200, heatsink_height_mm: 44, voltage_v: 1.35, extra: null },
  { id: "ram-08", category: "ram", type: "DDR4", model: "팀그룹 T-Force DELTA RGB DDR4-3600", speed_mhz: 3600, heatsink_height_mm: 41, voltage_v: 1.35, extra: null },
  { id: "ram-09", category: "ram", type: "DDR4", model: "팀그룹 T-Force DELTA RGB DDR4-3600 고클럭형", speed_mhz: 3600, heatsink_height_mm: 41, voltage_v: 1.35, extra: null },
  { id: "ram-10", category: "ram", type: "DDR4", model: "실리콘파워 XPOWER Zenith DDR4-3600", speed_mhz: 3600, heatsink_height_mm: null, voltage_v: null, extra: null },
];

export const GPUS: GPU[] = [
  { id: "gpu-01", category: "gpu", series: "RTX50", model: "NVIDIA GeForce RTX 5090 Founders Edition", vram_gb: 32, tdp_w: 575, connector: "16핀", recommended_psu_w: 1000, length_mm: 304, thickness: "3슬롯(61mm)", fans: 2, verified: true, extra: null },
  { id: "gpu-02", category: "gpu", series: "RTX50", model: "PALIT 지포스 RTX 5080 GAMINGPRO D7 16GB", vram_gb: 16, tdp_w: 360, connector: "16핀", recommended_psu_w: 850, length_mm: 331.9, thickness: "3슬롯(60mm)", fans: 3, verified: true, extra: null },
  { id: "gpu-03", category: "gpu", series: "RTX50", model: "MSI 지포스 RTX 5070 Ti 게이밍 트리오 OC 플러스 D7 16GB", vram_gb: 16, tdp_w: 300, connector: "16핀", recommended_psu_w: 750, length_mm: 338, thickness: "3슬롯(50mm)", fans: 3, verified: true, extra: null },
  { id: "gpu-04", category: "gpu", series: "RTX50", model: "MSI 지포스 RTX 5070 벤투스 3X OC D7 12GB", vram_gb: 12, tdp_w: 250, connector: "16핀", recommended_psu_w: 650, length_mm: 338, thickness: "3슬롯(50mm)", fans: 3, verified: true, extra: null },
  { id: "gpu-05", category: "gpu", series: "RTX50", model: "PALIT 지포스 RTX 5060 Ti Infinity 3 D7 16GB", vram_gb: 16, tdp_w: 180, connector: "8핀", recommended_psu_w: 600, length_mm: 291.9, thickness: "3슬롯", fans: 3, verified: true, extra: null },
  { id: "gpu-06", category: "gpu", series: "RTX50", model: "갤럭시 GALAX 지포스 RTX 5060 WHITE OC D7 8GB", vram_gb: 8, tdp_w: 140, connector: "8핀", recommended_psu_w: 550, length_mm: 250, thickness: "2슬롯", fans: 2, verified: true, extra: null },
  { id: "gpu-07", category: "gpu", series: "RTX40", model: "NVIDIA GeForce RTX 4090 Founders Edition", vram_gb: 24, tdp_w: 450, connector: "16핀", recommended_psu_w: 850, length_mm: 304, thickness: "3슬롯(61mm)", fans: 2, verified: true, extra: null },
  { id: "gpu-08", category: "gpu", series: "RTX40", model: "ASUS TUF Gaming GeForce RTX 4080 SUPER", vram_gb: 16, tdp_w: 320, connector: "16핀", recommended_psu_w: 750, length_mm: 348.2, thickness: "3.65슬롯(72.6mm)", fans: 3, verified: true, extra: null },
  { id: "gpu-09", category: "gpu", series: "RTX40", model: "MSI GeForce RTX 4070 SUPER Gaming X Slim", vram_gb: 12, tdp_w: 220, connector: "16핀", recommended_psu_w: 650, length_mm: 307, thickness: "2.3슬롯(46mm)", fans: 3, verified: true, extra: null },
  { id: "gpu-10", category: "gpu", series: "RTX40", model: "이엠텍 지포스 RTX 4060 Ti MIRACLE X3", vram_gb: 8, tdp_w: 160, connector: "8핀", recommended_psu_w: 550, length_mm: 282, thickness: "2.2슬롯(44mm)", fans: 3, verified: true, extra: null },
  { id: "gpu-11", category: "gpu", series: "RTX40", model: "갤럭시 GALAX 지포스 RTX 4060 2X OC V2", vram_gb: 8, tdp_w: 115, connector: "8핀", recommended_psu_w: 500, length_mm: 251, thickness: "2슬롯(40mm)", fans: 2, verified: true, extra: null },
  { id: "gpu-12", category: "gpu", series: "RX7000", model: "SAPPHIRE 라데온 RX 7900 XTX NITRO+ Vapor-X", vram_gb: 24, tdp_w: 420, connector: "8핀x3", recommended_psu_w: 850, length_mm: 320, thickness: "3.5슬롯(71.6mm)", fans: 3, verified: true, extra: null },
  { id: "gpu-13", category: "gpu", series: "RX7000", model: "ASUS TUF Gaming 라데온 RX 7800 XT", vram_gb: 16, tdp_w: 263, connector: "8핀x2", recommended_psu_w: 700, length_mm: 319.8, thickness: "2.96슬롯(59.2mm)", fans: 3, verified: true, extra: null },
  { id: "gpu-14", category: "gpu", series: "RX7000", model: "GIGABYTE 라데온 RX 7600 XT GAMING OC", vram_gb: 16, tdp_w: 190, connector: "8핀", recommended_psu_w: 600, length_mm: 282, thickness: "2.5슬롯(53mm)", fans: 3, verified: true, extra: null },
  { id: "gpu-15", category: "gpu", series: "RX7000", model: "SAPPHIRE 라데온 RX 7600 PULSE", vram_gb: 8, tdp_w: 165, connector: "8핀", recommended_psu_w: 550, length_mm: 240, thickness: "2.2슬롯(44mm)", fans: 2, verified: true, extra: null },
  { id: "gpu-16", category: "gpu", series: "RTX40", model: "기가바이트 지포스 RTX 4070 Ti SUPER EAGLE OC ICE D6X 16GB", vram_gb: 16, tdp_w: 285, connector: "16핀", recommended_psu_w: 750, length_mm: 261, thickness: "2.5슬롯(50mm)", fans: 3, verified: true, extra: null },
  { id: "gpu-17", category: "gpu", series: "RTX40", model: "MSI 지포스 RTX 4060 Ti 벤투스 2X 블랙 OC D6 16GB", vram_gb: 16, tdp_w: 165, connector: "8핀", recommended_psu_w: 550, length_mm: 199, thickness: "2슬롯(42mm)", fans: 2, verified: true, extra: null },
  { id: "gpu-18", category: "gpu", series: "RX9000", model: "ASUS PRIME 라데온 RX 9070 XT OC D6 16GB", vram_gb: 16, tdp_w: null, connector: "8핀x3", recommended_psu_w: 750, length_mm: 312, thickness: "3슬롯(50mm)", fans: 3, verified: true, extra: {"boost_mhz": 3010, "oc_mhz": 3030, "pcie": "PCIe5.0x16", "source": "danawa"} },
  { id: "gpu-19", category: "gpu", series: "RX9000", model: "SAPPHIRE 라데온 RX 9070 XT NITRO+ OC D6 16GB", vram_gb: 16, tdp_w: 330, connector: "16핀(12V2x6)x1", recommended_psu_w: 750, length_mm: 330.8, thickness: "3슬롯(65.7mm)", fans: 3, verified: true, extra: {"boost_mhz": 3060, "pcie": "PCIe5.0x16", "power_phase": "16페이즈", "source": "danawa"} },
  { id: "gpu-20", category: "gpu", series: "RX9000", model: "GIGABYTE 라데온 RX 9070 XT GAMING OC D6 16GB", vram_gb: 16, tdp_w: null, connector: "8핀x3", recommended_psu_w: 850, length_mm: 288, thickness: "3슬롯(56mm)", fans: 3, verified: true, extra: {"boost_mhz": 3060, "pcie": "PCIe5.0x16", "source": "danawa"} },
  { id: "gpu-21", category: "gpu", series: "RX9000", model: "ASRock 라데온 RX 9070 XT CHALLENGER D6 16GB", vram_gb: 16, tdp_w: null, connector: "8핀x2", recommended_psu_w: 800, length_mm: 290, thickness: "3슬롯(56mm)", fans: 3, verified: true, extra: {"boost_mhz": 2970, "pcie": "PCIe5.0x16", "source": "danawa"} },
  { id: "gpu-22", category: "gpu", series: "RX9000", model: "XFX 라데온 RX 9070 XT SWIFT D6 16GB", vram_gb: 16, tdp_w: 304, connector: "8핀x2", recommended_psu_w: 800, length_mm: 325, thickness: "3슬롯(65mm)", fans: 3, verified: true, extra: {"base_mhz": 1660, "boost_mhz": 2970, "pcie": "PCIe5.0x16", "source": "danawa"} },
  { id: "gpu-23", category: "gpu", series: "RX9000", model: "PowerColor 라데온 RX 9070 XT Reaper D6 16GB", vram_gb: 16, tdp_w: null, connector: "8핀x2", recommended_psu_w: 750, length_mm: 289, thickness: "3슬롯(41mm)", fans: 3, verified: true, extra: {"boost_mhz": 2970, "pcie": "PCIe5.0x16", "source": "danawa"} },
  { id: "gpu-24", category: "gpu", series: "RX9000", model: "XFX 라데온 RX 9060 XT SWIFT DUAL OC D6 16GB", vram_gb: 16, tdp_w: 182, connector: "8핀x1", recommended_psu_w: 450, length_mm: 270, thickness: "2슬롯(49mm)", fans: 2, verified: true, extra: {"base_mhz": 1900, "boost_mhz": 3320, "pcie": "PCIe5.0x16", "source": "danawa"} },
];

export const PSUS: PSU[] = [
  { id: "psu-01", category: "psu", model: "FSP Hydro GE 650W", watt: 650, grade: "골드", length_mm: 170, atx_version: "ATX12V v2.4", form_factor: "ATX", extra: null },
  { id: "psu-02", category: "psu", model: "SuperFlower LEADEX III 650W", watt: 650, grade: "골드", length_mm: 165, atx_version: "ATX12V v2.32(구형)/ATX3.1(신형)", form_factor: "ATX", extra: {"note": "리비전별 표기 다름"} },
  { id: "psu-03", category: "psu", model: "XFX XTR 650W Gold", watt: 650, grade: "골드", length_mm: 170, atx_version: "ATX12V(구형)", form_factor: "ATX", extra: null },
  { id: "psu-04", category: "psu", model: "시소닉 NEW FOCUS V4 GX-750", watt: 750, grade: "골드", length_mm: 140, atx_version: "ATX3.1", form_factor: "ATX", extra: null },
  { id: "psu-05", category: "psu", model: "EVGA SUPERNOVA 750 GA", watt: 750, grade: "골드", length_mm: 150, atx_version: "ATX12V(구형)", form_factor: "ATX", extra: null },
  { id: "psu-06", category: "psu", model: "맥스엘리트 STARS GEMINI 750W", watt: 750, grade: "브론즈", length_mm: 145, atx_version: "ATX3.1", form_factor: "ATX", extra: null },
  { id: "psu-07", category: "psu", model: "마이크로닉스 Classic II 850W Gold", watt: 850, grade: "골드", length_mm: 140, atx_version: "ATX3.1", form_factor: "ATX", extra: null },
  { id: "psu-08", category: "psu", model: "SuperFlower LEADEX VII 850W", watt: 850, grade: "골드", length_mm: 150, atx_version: "ATX3.1", form_factor: "ATX", extra: null },
  { id: "psu-09", category: "psu", model: "시소닉 NEW FOCUS V4 GX-850", watt: 850, grade: "골드", length_mm: 140, atx_version: "ATX3.1", form_factor: "ATX", extra: null },
  { id: "psu-10", category: "psu", model: "시소닉 FOCUS(V4) GX-1000", watt: 1000, grade: "골드", length_mm: 140, atx_version: "ATX3.1", form_factor: "ATX", extra: null },
  { id: "psu-11", category: "psu", model: "마이크로닉스 Classic II 1050W 230V EU", watt: 1050, grade: "골드", length_mm: 140, atx_version: "ATX3.0/구형리비전 12VHPWR", form_factor: "ATX", extra: {"note": "리비전별 표기 다름"} },
  { id: "psu-12", category: "psu", model: "FSP HYDRO G PRO 1000W", watt: 1000, grade: "골드", length_mm: 150, atx_version: "ATX3.0", form_factor: "ATX", extra: null },
];

export const CASES: PCCase[] = [
  { id: "case-01", category: "case", model: "DAVEN D7 Mesh 세븐팬", tower_type: "미들타워", supported_mb: "ATX;M-ATX;Mini-ITX", gpu_max_length_mm: 400, cpu_cooler_max_height_mm: 170, psu_support: "표준-ATX", psu_position: "하단후면", psu_max_length_mm: 200, radiator_top_mm: "280/360", radiator_front_mm: 360, radiator_side_mm: "불가" },
  { id: "case-02", category: "case", model: "darkFlash DS500 RGB", tower_type: "미들타워", supported_mb: "ATX;M-ATX;Mini-ITX", gpu_max_length_mm: 405, cpu_cooler_max_height_mm: 165, psu_support: "표준-ATX", psu_position: "하단후면", psu_max_length_mm: 170, radiator_top_mm: "240/280", radiator_front_mm: "240/280/360", radiator_side_mm: "불가" },
  { id: "case-03", category: "case", model: "마이크로닉스 WIZMAX 우드리안 MAX", tower_type: "빅타워", supported_mb: "ATX;ATX(후면커넥터);M-ATX;M-ATX(후면커넥터);Mini-ITX", gpu_max_length_mm: 410, cpu_cooler_max_height_mm: 160, psu_support: "표준-ATX", psu_position: "상단", psu_max_length_mm: null, radiator_top_mm: "280/360", radiator_front_mm: 360, radiator_side_mm: "불가" },
  { id: "case-04", category: "case", model: "Antec FLUX PRO MESH", tower_type: "빅타워", supported_mb: "E-ATX;ATX;M-ATX;Mini-ITX", gpu_max_length_mm: 455, cpu_cooler_max_height_mm: 190, psu_support: "표준-ATX", psu_position: "하단후면", psu_max_length_mm: "180-300", radiator_top_mm: "360/420", radiator_front_mm: "360/420", radiator_side_mm: "불가" },
  { id: "case-05", category: "case", model: "Antec FLUX SE MESH BTF", tower_type: "미들타워", supported_mb: "E-ATX;ATX(후면커넥터);M-ATX(후면커넥터);Mini-ITX", gpu_max_length_mm: 408, cpu_cooler_max_height_mm: 180, psu_support: "표준-ATX", psu_position: "하단후면", psu_max_length_mm: 235, radiator_top_mm: "280/360", radiator_front_mm: 360, radiator_side_mm: "불가" },
  { id: "case-06", category: "case", model: "Antec FLUX MESH BTF", tower_type: "미들타워", supported_mb: "E-ATX;ATX(후면커넥터);M-ATX(후면커넥터);Mini-ITX", gpu_max_length_mm: 408, cpu_cooler_max_height_mm: 180, psu_support: "표준-ATX", psu_position: "하단후면", psu_max_length_mm: 235, radiator_top_mm: "280/360", radiator_front_mm: 360, radiator_side_mm: "불가" },
  { id: "case-07", category: "case", model: "LIAN LI LANCOOL 207", tower_type: "컴팩트ATX", supported_mb: "ATX;M-ATX;Mini-ITX", gpu_max_length_mm: 375, cpu_cooler_max_height_mm: 180, psu_support: "표준-ATX", psu_position: "전면", psu_max_length_mm: 160, radiator_top_mm: "280/360", radiator_front_mm: "불가", radiator_side_mm: "불가" },
  { id: "case-08", category: "case", model: "LIAN LI LANCOOL 216", tower_type: "미들타워", supported_mb: "E-ATX;ATX;M-ATX;Mini-ITX", gpu_max_length_mm: 392, cpu_cooler_max_height_mm: 180.5, psu_support: "표준-ATX", psu_position: "하단후면", psu_max_length_mm: 220, radiator_top_mm: "280/360", radiator_front_mm: "280/360", radiator_side_mm: "불가" },
  { id: "case-09", category: "case", model: "아이구주 HATCH 6 플렉스 메쉬 강화유리", tower_type: "미들타워", supported_mb: "ATX;M-ATX", gpu_max_length_mm: 325, cpu_cooler_max_height_mm: 160, psu_support: "표준-ATX", psu_position: "하단후면", psu_max_length_mm: null, radiator_top_mm: "불가", radiator_front_mm: "240/360", radiator_side_mm: "불가" },
  { id: "case-10", category: "case", model: "DAVEN D6 MESH 강화유리", tower_type: "미들타워", supported_mb: "ATX;M-ATX;Mini-ITX", gpu_max_length_mm: 330, cpu_cooler_max_height_mm: 173, psu_support: "표준-ATX", psu_position: "하단후면", psu_max_length_mm: "170-250", radiator_top_mm: 240, radiator_front_mm: "280/360", radiator_side_mm: "불가" },
  { id: "case-11", category: "case", model: "잘만 i8 백사십 터보", tower_type: "미들타워", supported_mb: "ATX;M-ATX;Mini-ITX", gpu_max_length_mm: 410, cpu_cooler_max_height_mm: 180, psu_support: "표준-ATX", psu_position: "하단후면", psu_max_length_mm: 200, radiator_top_mm: "280/360", radiator_front_mm: "280/360", radiator_side_mm: "불가" },
  { id: "case-12", category: "case", model: "HYTE Y70", tower_type: "빅타워", supported_mb: "E-ATX, ATX, M-ATX, Mini-ITX", gpu_max_length_mm: 422, cpu_cooler_max_height_mm: 180, psu_support: "표준-ATX", psu_position: "하단후면", psu_max_length_mm: 230, radiator_top_mm: "280/360", radiator_front_mm: "불가", radiator_side_mm: "280/360" },
];

export const SSDS: SSD[] = [
  { id: "ssd-01", category: "ssd", model: "Samsung 990 PRO 1TB", type: "M.2 NVMe", interface: "PCIe4.0x4" },
  { id: "ssd-02", category: "ssd", model: "Samsung 990 PRO 2TB", type: "M.2 NVMe", interface: "PCIe4.0x4" },
  { id: "ssd-03", category: "ssd", model: "Samsung 990 PRO 4TB", type: "M.2 NVMe", interface: "PCIe4.0x4" },
  { id: "ssd-04", category: "ssd", model: "Samsung 990 EVO Plus 1TB", type: "M.2 NVMe", interface: "PCIe4.0x4/PCIe5.0x2" },
  { id: "ssd-05", category: "ssd", model: "WD BLACK SN850X 1TB", type: "M.2 NVMe", interface: "PCIe4.0x4" },
  { id: "ssd-06", category: "ssd", model: "WD BLACK SN850X 2TB", type: "M.2 NVMe", interface: "PCIe4.0x4" },
  { id: "ssd-07", category: "ssd", model: "SK hynix Platinum P41 1TB", type: "M.2 NVMe", interface: "PCIe4.0x4" },
  { id: "ssd-08", category: "ssd", model: "Lexar NM790 1TB", type: "M.2 NVMe", interface: "PCIe4.0x4" },
  { id: "ssd-09", category: "ssd", model: "Crucial P5 Plus 1TB", type: "M.2 NVMe", interface: "PCIe4.0x4" },
  { id: "ssd-10", category: "ssd", model: "Crucial P5 Plus 2TB", type: "M.2 NVMe", interface: "PCIe4.0x4" },
  { id: "ssd-11", category: "ssd", model: "ADATA LEGEND 860 500GB", type: "M.2 NVMe", interface: "PCIe4.0x4" },
  { id: "ssd-12", category: "ssd", model: "KLEVV CRAS C910G 500GB", type: "M.2 NVMe", interface: "PCIe4.0x4" },
  { id: "ssd-13", category: "ssd", model: "KLEVV CRAS C910G 1TB", type: "M.2 NVMe", interface: "PCIe4.0x4" },
  { id: "ssd-14", category: "ssd", model: "Samsung 870 EVO 250GB", type: "SATA", interface: "SATA III" },
  { id: "ssd-15", category: "ssd", model: "Samsung 870 EVO 500GB", type: "SATA", interface: "SATA III" },
  { id: "ssd-16", category: "ssd", model: "Samsung 870 EVO 1TB", type: "SATA", interface: "SATA III" },
  { id: "ssd-17", category: "ssd", model: "Samsung 870 EVO 2TB", type: "SATA", interface: "SATA III" },
  { id: "ssd-18", category: "ssd", model: "Samsung 870 EVO 4TB", type: "SATA", interface: "SATA III" },
  { id: "ssd-19", category: "ssd", model: "Samsung 870 EVO 8TB", type: "SATA", interface: "SATA III" },
  { id: "ssd-20", category: "ssd", model: "Crucial MX500 500GB", type: "SATA", interface: "SATA III" },
  { id: "ssd-21", category: "ssd", model: "Crucial MX500 1TB", type: "SATA", interface: "SATA III" },
  { id: "ssd-22", category: "ssd", model: "Crucial MX500 2TB", type: "SATA", interface: "SATA III" },
  { id: "ssd-23", category: "ssd", model: "WD Blue 3D", type: "SATA", interface: "SATA III" },
  { id: "ssd-24", category: "ssd", model: "Transcend SSD230S", type: "SATA", interface: "SATA III" },
];

export const COOLERS: Cooler[] = [
  { id: "cooler-air-01", category: "cooler", model: "쿨러마스터 Hyper 212 LED Turbo", type: "air", height_mm: 163, radiator_size_mm: null, supported_sockets: "AM4;AM5;LGA1700;LGA1200;LGA115x;LGA2011;LGA2011-V3;LGA775", extra: {"width_mm": 120, "depth_mm": 108, "fan_size_mm": 120, "fan_count": 1} },
  { id: "cooler-air-02", category: "cooler", model: "DEEPCOOL AK620", type: "air", height_mm: 160, radiator_size_mm: null, supported_sockets: "AM4;AM5;LGA1851;LGA1700;LGA1200;LGA115x;LGA2066;LGA2011-V3", extra: {"width_mm": 129, "depth_mm": 138, "fan_size_mm": 120, "fan_count": 2, "tdp_rated_w": 260} },
  { id: "cooler-air-03", category: "cooler", model: "ID-COOLING SE-224-XT Basic", type: "air", height_mm: 154, radiator_size_mm: null, supported_sockets: "AM4;LGA1700;LGA1200;LGA115x;LGA2066;LGA2011", extra: {"width_mm": 120, "depth_mm": 73, "fan_size_mm": 120, "fan_count": 1, "note": "AM5 미지원(구형 브라켓 기준), XTS 버전만 LGA1851/AM5 지원"} },
  { id: "cooler-air-04", category: "cooler", model: "NOCTUA NH-D15", type: "air", height_mm: 165, radiator_size_mm: null, supported_sockets: "AM4;AM5;LGA1851;LGA1700;LGA1200;LGA115x", extra: {"width_mm": 150, "depth_mm": 161, "fan_size_mm": 140, "fan_count": 2} },
  { id: "cooler-aio-01", category: "cooler", model: "NZXT KRAKEN 240", type: "aqua", height_mm: null, radiator_size_mm: 240, supported_sockets: "AM4;AM5;TR4;sTRX4;LGA1851;LGA1700;LGA1200;LGA115x", extra: {"radiator_length_mm": 275, "radiator_thickness_mm": 30, "fan_size_mm": 120, "fan_count": 2} },
  { id: "cooler-aio-02", category: "cooler", model: "NZXT KRAKEN 280", type: "aqua", height_mm: null, radiator_size_mm: 280, supported_sockets: "AM4;AM5;TR4;sTRX4;LGA1851;LGA1700;LGA1200;LGA115x", extra: {"radiator_length_mm": 315, "radiator_thickness_mm": 30, "fan_size_mm": 140, "fan_count": 2} },
  { id: "cooler-aio-03", category: "cooler", model: "NZXT KRAKEN 360", type: "aqua", height_mm: null, radiator_size_mm: 360, supported_sockets: "AM4;AM5;TR4;sTRX4;LGA1851;LGA1700;LGA1200;LGA115x", extra: {"radiator_length_mm": 394, "radiator_thickness_mm": 27, "fan_size_mm": 120, "fan_count": 3} },
  { id: "cooler-aio-04", category: "cooler", model: "ARCTIC Liquid Freezer III 360", type: "aqua", height_mm: null, radiator_size_mm: 360, supported_sockets: "AM4;AM5;LGA1851;LGA1700", extra: {"radiator_length_mm": 398, "radiator_thickness_mm": 38, "fan_size_mm": 120, "fan_count": 3, "vrm_fan": true} },
];

export const SEED = {
  cpu: CPUS,
  motherboard: MOTHERBOARDS,
  ram: RAMS,
  ssd: SSDS,
  gpu: GPUS,
  psu: PSUS,
  case: CASES,
  cooler: COOLERS,
} as const;
